-- Single source of truth for the per-language smoke test
-- (tests/nvim/spec/language_smoke_spec.lua). Each row pins, for ONE fixture:
--   fixture     path under tests/nvim/fixtures/
--   filetype    the filetype Neovim must detect when the fixture opens
--   parser      the treesitter parser for that filetype (false = none)
--   bundled     true when Neovim bundles a matched parser+query for it (c, lua,
--               markdown, query, vim) -- those must NOT be in treesitter_parsers
--               (installing nvim-treesitter's would override the built-in and
--               break the bundled query), so the spec asserts they are absent
--   formatters  conform formatters_by_ft for that filetype ({} = none)
--   lsp         the LSP server expected for that filetype (false = none)
--   lsp_gated   true when the server only enables if its runtime is present
--               (e.g. powershell_es needs pwsh), so Tier 2 skips it otherwise
--
-- Keep this in sync with nvim/lua/plugins/{treesitter,conform,lsp-config}.lua.
-- The spec asserts they agree, so drift fails CI -- this is the single place
-- that would have caught the jsonc "skipping unsupported language" bug.
return {
  {
    fixture = "sample.lua",
    filetype = "lua",
    parser = "lua",
    bundled = true,
    formatters = { "stylua" },
    lsp = "lua_ls",
  },
  {
    fixture = "sample.py",
    filetype = "python",
    parser = "python",
    formatters = { "ruff_fix", "ruff_format" },
    lsp = "pyright",
  },
  {
    fixture = "sample.c",
    filetype = "c",
    parser = "c",
    bundled = true,
    formatters = { "clang_format" },
    lsp = "clangd",
  },
  { fixture = "sample.cpp", filetype = "cpp", parser = "cpp", formatters = { "clang_format" }, lsp = "clangd" },
  { fixture = "sample.rs", filetype = "rust", parser = "rust", formatters = { "rustfmt" }, lsp = "rust_analyzer" },
  { fixture = "CMakeLists.txt", filetype = "cmake", parser = "cmake", formatters = { "gersemi" }, lsp = "neocmake" },
  { fixture = "sample.sh", filetype = "sh", parser = "bash", formatters = { "shfmt" }, lsp = "bashls" },
  { fixture = "sample.bash", filetype = "sh", parser = "bash", formatters = { "shfmt" }, lsp = "bashls" },
  { fixture = "sample.zsh", filetype = "zsh", parser = "zsh", formatters = { "shfmt" }, lsp = "bashls" },
  { fixture = "sample.bat", filetype = "dosbatch", parser = false, formatters = {}, lsp = false },
  { fixture = "sample.js", filetype = "javascript", parser = "javascript", formatters = { "prettier" }, lsp = false },
  {
    fixture = "sample.jsx",
    filetype = "javascriptreact",
    parser = "javascript",
    formatters = { "prettier" },
    lsp = false,
  },
  { fixture = "sample.ts", filetype = "typescript", parser = "typescript", formatters = { "prettier" }, lsp = false },
  { fixture = "sample.tsx", filetype = "typescriptreact", parser = "tsx", formatters = { "prettier" }, lsp = false },
  { fixture = "index.html", filetype = "html", parser = "html", formatters = { "prettier" }, lsp = false },
  { fixture = "style.css", filetype = "css", parser = "css", formatters = { "prettier" }, lsp = false },
  { fixture = "style.scss", filetype = "scss", parser = "scss", formatters = { "prettier" }, lsp = false },
  { fixture = "Component.vue", filetype = "vue", parser = "vue", formatters = { "prettier" }, lsp = false },
  { fixture = "Component.svelte", filetype = "svelte", parser = "svelte", formatters = {}, lsp = false },
  { fixture = "page.astro", filetype = "astro", parser = "astro", formatters = {}, lsp = false },
  { fixture = "schema.graphql", filetype = "graphql", parser = "graphql", formatters = { "prettier" }, lsp = false },
  {
    fixture = "sample.ps1",
    filetype = "ps1",
    parser = "powershell",
    formatters = {},
    lsp = "powershell_es",
    lsp_gated = true,
  },
  { fixture = "sample.json", filetype = "json", parser = "json", formatters = { "prettier" }, lsp = "jsonls" },
  { fixture = "sample.jsonc", filetype = "jsonc", parser = false, formatters = { "prettier" }, lsp = "jsonls" },
  { fixture = "data.json5", filetype = "json5", parser = "json5", formatters = { "prettier" }, lsp = false },
  { fixture = "sample.yaml", filetype = "yaml", parser = "yaml", formatters = { "prettier" }, lsp = "yamlls" },
  { fixture = "sample.yml", filetype = "yaml", parser = "yaml", formatters = { "prettier" }, lsp = "yamlls" },
  { fixture = "sample.toml", filetype = "toml", parser = "toml", formatters = {}, lsp = false },
  { fixture = "sample.xml", filetype = "xml", parser = "xml", formatters = {}, lsp = false },
  { fixture = "Project.csproj", filetype = "xml", parser = "xml", formatters = {}, lsp = false },
  { fixture = "App.sln", filetype = "solution", parser = false, formatters = {}, lsp = false },
  { fixture = ".curlrc", filetype = "conf", parser = false, formatters = {}, lsp = false },
  { fixture = "sample.curlrc", filetype = "conf", parser = false, formatters = {}, lsp = false },
  { fixture = "Views/Home/Index.cshtml", filetype = "razor", parser = "razor", formatters = {}, lsp = false },
  { fixture = "sample.csv", filetype = "csv", parser = "csv", formatters = {}, lsp = false },
  { fixture = "Dockerfile", filetype = "dockerfile", parser = "dockerfile", formatters = {}, lsp = false },
  { fixture = "sample.hcl", filetype = "hcl", parser = "hcl", formatters = {}, lsp = false },
  { fixture = "main.tf", filetype = "terraform", parser = "terraform", formatters = {}, lsp = false },
  { fixture = "Makefile", filetype = "make", parser = "make", formatters = {}, lsp = false },
  { fixture = "sample.http", filetype = "http", parser = "http", formatters = {}, lsp = false },
  { fixture = "sample.sql", filetype = "sql", parser = "sql", formatters = {}, lsp = false },
  { fixture = "schema.proto", filetype = "proto", parser = "proto", formatters = {}, lsp = false },
  { fixture = "schema.prisma", filetype = "prisma", parser = "prisma", formatters = {}, lsp = false },
  { fixture = "flake.nix", filetype = "nix", parser = "nix", formatters = {}, lsp = false },
  { fixture = "sample.ini", filetype = "dosini", parser = "ini", formatters = {}, lsp = false },
  { fixture = ".editorconfig", filetype = "editorconfig", parser = "editorconfig", formatters = {}, lsp = false },
  { fixture = ".gitignore", filetype = "gitignore", parser = "gitignore", formatters = {}, lsp = false },
  { fixture = ".gitconfig", filetype = "gitconfig", parser = "git_config", formatters = {}, lsp = false },
  { fixture = "git-rebase-todo", filetype = "gitrebase", parser = "git_rebase", formatters = {}, lsp = false },
  { fixture = "ssh_config", filetype = "sshconfig", parser = "ssh_config", formatters = {}, lsp = false },
  { fixture = "requirements.txt", filetype = "requirements", parser = "requirements", formatters = {}, lsp = false },
  { fixture = "config.fish", filetype = "fish", parser = "fish", formatters = {}, lsp = false },
  { fixture = "script.nu", filetype = "nu", parser = "nu", formatters = {}, lsp = false },
  { fixture = "justfile", filetype = "just", parser = "just", formatters = {}, lsp = false },
  { fixture = "meson.build", filetype = "meson", parser = "meson", formatters = {}, lsp = false },
  { fixture = "build.ninja", filetype = "ninja", parser = "ninja", formatters = {}, lsp = false },
  { fixture = "nginx.conf", filetype = "nginx", parser = "nginx", formatters = {}, lsp = false },
  { fixture = "filter.jq", filetype = "jq", parser = "jq", formatters = {}, lsp = false },
  { fixture = "sample.kdl", filetype = "kdl", parser = "kdl", formatters = {}, lsp = false },
  { fixture = "app.desktop", filetype = "desktop", parser = "desktop", formatters = {}, lsp = false },
  { fixture = "sample.latex", filetype = "tex", parser = "latex", formatters = {}, lsp = false },
  { fixture = "refs.bib", filetype = "bib", parser = "bibtex", formatters = {}, lsp = false },
  { fixture = "note.typ", filetype = "typst", parser = "typst", formatters = {}, lsp = false },
  { fixture = "diagram.mmd", filetype = "mermaid", parser = "mermaid", formatters = {}, lsp = false },
  { fixture = "shader.glsl", filetype = "glsl", parser = "glsl", formatters = {}, lsp = false },
  { fixture = "shader.wgsl", filetype = "wgsl", parser = "wgsl", formatters = {}, lsp = false },
  { fixture = "config.ron", filetype = "ron", parser = "ron", formatters = {}, lsp = false },
  { fixture = "sample.go", filetype = "go", parser = "go", formatters = {}, lsp = false },
  { fixture = "go.mod", filetype = "gomod", parser = "gomod", formatters = {}, lsp = false },
  { fixture = "go.sum", filetype = "gosum", parser = "gosum", formatters = {}, lsp = false },
  { fixture = "go.work", filetype = "gowork", parser = "gowork", formatters = {}, lsp = false },
  { fixture = "sample.cs", filetype = "cs", parser = "c_sharp", formatters = {}, lsp = false },
  { fixture = "sample.fs", filetype = "fsharp", parser = "fsharp", formatters = {}, lsp = false },
  { fixture = "Main.java", filetype = "java", parser = "java", formatters = {}, lsp = false },
  { fixture = "Main.kt", filetype = "kotlin", parser = "kotlin", formatters = {}, lsp = false },
  { fixture = "Main.scala", filetype = "scala", parser = "scala", formatters = {}, lsp = false },
  { fixture = "sample.php", filetype = "php", parser = "php", formatters = {}, lsp = false },
  { fixture = "sample.rb", filetype = "ruby", parser = "ruby", formatters = {}, lsp = false },
  { fixture = "sample.pl", filetype = "perl", parser = "perl", formatters = {}, lsp = false },
  { fixture = "main.swift", filetype = "swift", parser = "swift", formatters = {}, lsp = false },
  { fixture = "main.zig", filetype = "zig", parser = "zig", formatters = {}, lsp = false },
  { fixture = "sample.s", filetype = "asm", parser = "asm", formatters = {}, lsp = false },
  { fixture = "sample.nasm", filetype = "nasm", parser = "nasm", formatters = {}, lsp = false },
  { fixture = "app.dart", filetype = "dart", parser = "dart", formatters = {}, lsp = false },
  { fixture = "lib.ex", filetype = "elixir", parser = "elixir", formatters = {}, lsp = false },
  { fixture = "server.erl", filetype = "erlang", parser = "erlang", formatters = {}, lsp = false },
  { fixture = "core.clj", filetype = "clojure", parser = "clojure", formatters = {}, lsp = false },
  { fixture = "Main.hs", filetype = "haskell", parser = "haskell", formatters = {}, lsp = false },
  { fixture = "module.ml", filetype = "ocaml", parser = "ocaml", formatters = {}, lsp = false },
  { fixture = "script.r", filetype = "r", parser = "r", formatters = {}, lsp = false },
  { fixture = "Contract.sol", filetype = "solidity", parser = "solidity", formatters = {}, lsp = false },
  { fixture = "main.jl", filetype = "julia", parser = "julia", formatters = {}, lsp = false },
  { fixture = "program.f90", filetype = "fortran", parser = "fortran", formatters = {}, lsp = false },
  { fixture = "program.pas", filetype = "pascal", parser = "pascal", formatters = {}, lsp = false },
  { fixture = "main.adb", filetype = "ada", parser = "ada", formatters = {}, lsp = false },
  { fixture = "build.gradle", filetype = "groovy", parser = "groovy", formatters = {}, lsp = false },
  { fixture = "sample.m", filetype = "matlab", parser = "matlab", formatters = {}, lsp = false },
  { fixture = "main.gleam", filetype = "gleam", parser = "gleam", formatters = {}, lsp = false },
  { fixture = "main.qml", filetype = "qml", parser = "qmljs", formatters = {}, lsp = false },
  { fixture = "main.bicep", filetype = "bicep", parser = "bicep", formatters = {}, lsp = false },
  { fixture = "Earthfile", filetype = "earthfile", parser = "earthfile", formatters = {}, lsp = false },
  {
    fixture = "sample.md",
    filetype = "markdown",
    parser = "markdown",
    bundled = true,
    formatters = { "prettier" },
    lsp = false,
  },
  { fixture = "sample.vim", filetype = "vim", parser = "vim", bundled = true, formatters = {}, lsp = false },
  {
    fixture = "queries/lua/highlights.scm",
    filetype = "query",
    parser = "query",
    bundled = true,
    formatters = {},
    lsp = false,
  },
  { fixture = "sample.diff", filetype = "diff", parser = "diff", formatters = {}, lsp = false },
  { fixture = "COMMIT_EDITMSG", filetype = "gitcommit", parser = "gitcommit", formatters = {}, lsp = false },
}
