package installer

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
)

func sentinelController(t *testing.T) (Controller, *ProfileDriver) {
	t.Helper()
	c, d, _ := profileController(t)
	d.Targets = map[string][]ProfileTarget{}
	if err := configureSentinel(d, ConfigFolders{Home: c.Home}, SentinelLocations{}); err != nil {
		t.Fatal(err)
	}
	c.Catalog = &Catalog{Schema: 1, Resources: []Resource{
		{ID: "sentinel", Name: "Sentinel", Capability: true, Requires: []string{sentinelResource}},
		{ID: sentinelResource, Name: "Global policy", Action: "sentinel", Scope: "user"},
	}}
	if err := c.Catalog.Validate(); err != nil {
		t.Fatal(err)
	}
	return c, d
}

func TestSentinelPinnedPolicyAndProvenance(t *testing.T) {
	data, err := os.ReadFile("sentinel/provenance.json")
	if err != nil {
		t.Fatal(err)
	}
	var provenance struct {
		Version      string `json:"version"`
		Commit       string `json:"commit"`
		PolicySHA256 string `json:"policy_sha256"`
		BundleSHA256 string `json:"bundle_sha256"`
	}
	if err := json.Unmarshal(data, &provenance); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256([]byte(sentinelPolicy))
	if provenance.Version != sentinelVersion || provenance.Commit != sentinelCommit || provenance.PolicySHA256 != sentinelPolicySHA256 || hex.EncodeToString(sum[:]) != sentinelPolicySHA256 || !strings.Contains(sentinelPolicy, "<!-- version: "+sentinelVersion+"  sha256: "+provenance.BundleSHA256+" -->") {
		t.Fatal("generated policy no longer matches its reviewed immutable provenance")
	}
	if got, err := renderSentinelBlock(nil, sentinelPolicy); err != nil || string(got) != sentinelPolicy {
		t.Fatal("fresh policy differs from upstream generated bytes", err)
	}
}

func TestSentinelConsumerLocationsAreExplicitAndConstructionIsWriteFree(t *testing.T) {
	c, _ := sentinelController(t)
	for _, key := range []string{"CODEX_HOME", "XDG_CONFIG_HOME", "PI_CODING_AGENT_DIR"} {
		t.Setenv(key, filepath.Join(c.Home, "caller-must-not-be-used"))
	}
	for _, targetOS := range []string{"darwin", "linux", "windows"} {
		t.Run(targetOS, func(t *testing.T) {
			for _, custom := range []bool{false, true} {
				locations := SentinelLocations{}
				want := []string{filepath.Join(c.Home, ".codex", "AGENTS.md"), filepath.Join(c.Home, ".claude", "CLAUDE.md"), filepath.Join(c.Home, ".config", "opencode", "AGENTS.md"), filepath.Join(c.Home, ".pi", "agent", "AGENTS.md")}
				if custom {
					locations = SentinelLocations{filepath.Join(c.Home, "custom codex"), filepath.Join(c.Home, "custom config"), filepath.Join(c.Home, "custom pi")}
					want[0], want[2], want[3] = filepath.Join(locations.CodexHome, "AGENTS.md"), filepath.Join(locations.ConfigHome, "opencode", "AGENTS.md"), filepath.Join(locations.PiAgentDir, "AGENTS.md")
				}
				d := &ProfileDriver{Directory: filepath.Join(c.Home, "state"), Windows: targetOS == "windows"}
				if err := configureSentinel(d, ConfigFolders{Home: c.Home, Config: filepath.Join(c.Home, "unrelated-appdata")}, locations); err != nil {
					t.Fatal(err)
				}
				for index, target := range d.Targets[sentinelResource] {
					if target.Path != want[index] || target.Script != sentinelPolicy {
						t.Fatal("wrong pinned consumer location or policy", target.Path, want[index])
					}
					if _, err := os.Lstat(filepath.Dir(target.Path)); !os.IsNotExist(err) {
						t.Fatal("constructor created a consumer directory", target.Path, err)
					}
				}
			}
		})
	}
	for _, locations := range []SentinelLocations{{CodexHome: "relative"}, {ConfigHome: filepath.Join(c.Home, "bad") + "\n"}, {PiAgentDir: filepath.Join(c.Home, ".codex")}} {
		if err := configureSentinel(&ProfileDriver{Directory: filepath.Join(c.Home, "state")}, ConfigFolders{Home: c.Home}, locations); err == nil {
			t.Fatal("accepted unsafe or overlapping consumer paths", locations)
		}
	}
}

func TestSentinelBlocksPreserveEncodingAndPersonalBytes(t *testing.T) {
	fixtures := [][]byte{nil, []byte("personal prose"), []byte("personal café\n"), []byte("personal\r\n"), {0xef, 0xbb, 0xbf}}
	for _, bom := range [][]byte{{0xff, 0xfe}, {0xfe, 0xff}} {
		encode, _, err := profileEncoding(bom)
		if err != nil {
			t.Fatal(err)
		}
		fixtures = append(fixtures, append(bytes.Clone(bom), encode("personal café 🌍\r\n")...))
	}
	for _, before := range fixtures {
		block, err := renderProfileBlock(before, sentinelResource, sentinelPolicy)
		if err != nil {
			t.Fatal(err)
		}
		installed, old, err := replaceProfileBlock(before, sentinelResource, block)
		if err != nil || len(old) != 0 {
			t.Fatal(err, string(old))
		}
		desired, err := renderProfileBlock(installed, sentinelResource, sentinelPolicy)
		if err != nil || !bytes.Equal(desired, block) {
			t.Fatal("installation changes its own desired identity", err)
		}
		again, _, err := replaceProfileBlock(installed, sentinelResource, desired)
		if err != nil || !bytes.Equal(again, installed) {
			t.Fatal("repeat changes policy", err)
		}
		restored, _, err := replaceProfileBlock(installed, sentinelResource, nil)
		if err != nil || !bytes.Equal(restored, before) {
			t.Fatalf("removal changed personal bytes: %x != %x: %v", restored, before, err)
		}
	}
}

func TestSentinelRejectsAmbiguousPolicyWithoutChangingFiles(t *testing.T) {
	for _, bad := range []string{sentinelBegin + "\nunterminated\n", sentinelEnd + "\n", sentinelPolicy + sentinelPolicy, "prose " + sentinelPolicy, strings.Replace(sentinelPolicy, sentinelEnd, sentinelEnd+" trailing", 1), strings.Replace(sentinelPolicy, sentinelBegin, "<!-- AGENT-RULES:BEGIN unexpected -->", 1)} {
		c, d := sentinelController(t)
		path := d.Targets[sentinelResource][0].Path
		writeConfigFixture(t, path, bad)
		plan, err := c.Preview(context.Background(), Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}})
		if err != nil {
			t.Fatal(err)
		}
		blocked := false
		for _, op := range plan.Operations {
			blocked = blocked || op.Resource == sentinelResource && op.Action == "pending"
		}
		if !blocked {
			t.Fatal("malformed policy was offered for installation", plan)
		}
		got, err := os.ReadFile(path)
		if err != nil || string(got) != bad {
			t.Fatal("inspection changed malformed policy", err)
		}
	}
}

func TestSentinelLifecyclePreservesAllFourConsumerPolicies(t *testing.T) {
	c, d := sentinelController(t)
	original := "# Personal policy\r\nKeep my instructions intact."
	for _, target := range d.Targets[sentinelResource] {
		writeConfigFixture(t, target.Path, original)
	}
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}})
	for _, target := range d.Targets[sentinelResource] {
		data, err := os.ReadFile(target.Path)
		if err != nil {
			t.Fatal(err)
		}
		writeConfigFixture(t, target.Path, string(data)+"Later personal instruction.\r\n")
	}
	check, err := c.Dispatch(context.Background(), Request{Schema: 1, Mode: "check"})
	if err != nil || check.Status != "ready" {
		t.Fatal("outside prose invalidates policy", check, err)
	}
	for index := range d.Targets[sentinelResource] {
		d.Targets[sentinelResource][index].Script = strings.Replace(sentinelPolicy, "version: 0.1.2", "version: 0.1.3", 1)
	}
	dispatchApproved(t, c, Request{Schema: 1, Mode: "update"})
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{}})
	for _, target := range d.Targets[sentinelResource] {
		got, err := os.ReadFile(target.Path)
		if err != nil || string(got) != original+"Later personal instruction.\r\n" {
			t.Fatal("removal lost outside policy", target.Path, string(got), err)
		}
	}
}

func TestSentinelExplicitAdoptionRestoresEarlierPolicyAndKeepsLaterEdits(t *testing.T) {
	for _, identical := range []bool{false, true} {
		t.Run(map[bool]string{false: "earlier", true: "identical"}[identical], func(t *testing.T) {
			c, d := sentinelController(t)
			policy := sentinelPolicy
			if !identical {
				policy = "<!-- AGENT-RULES:BEGIN -->\nEarlier personal policy.\n" + sentinelEnd
			}
			original := "My prose.\n\n" + policy + "\nTrailing prose."
			for _, target := range d.Targets[sentinelResource] {
				writeConfigFixture(t, target.Path, original)
			}
			request := Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}}
			plan, err := c.Preview(context.Background(), request)
			if err != nil {
				t.Fatal(err)
			}
			for _, op := range plan.Operations {
				if op.Resource == sentinelResource && (op.Action == "install" || op.Action == "adopt") {
					t.Fatal("unrequested adoption", op)
				}
			}
			request.Adopt = []string{sentinelResource}
			dispatchApproved(t, c, request)
			before, err := LoadState(c.StatePath, c.Home)
			if err != nil || !before.Receipts[sentinelResource].Adopted || before.Receipts[sentinelResource].Ownership != "created" {
				t.Fatal("explicit adoption failed", before, err)
			}
			path := d.Targets[sentinelResource][0].Path
			installed, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			edited := bytes.Replace(installed, []byte("# Operating Contract"), []byte("# My edited contract"), 1)
			writeConfigFixture(t, path, string(edited))
			check, err := c.Dispatch(context.Background(), Request{Schema: 1, Mode: "check"})
			if err != nil || check.Status != "needs-action" {
				t.Fatal("edited managed policy was reported healthy", check, err)
			}
			dispatchApproved(t, c, Request{Schema: 1, Mode: "repair", Adopt: []string{sentinelResource}})
			after, err := LoadState(c.StatePath, c.Home)
			if err != nil || after.Receipts[sentinelResource].Recovery != before.Receipts[sentinelResource].Recovery || !sameArtifact(after.Receipts[sentinelResource].Before, before.Receipts[sentinelResource].Before) {
				t.Fatal("replacement reset original baseline", err)
			}
			journal, err := d.readJournal(sentinelResource, after.Receipts[sentinelResource])
			if err != nil {
				t.Fatal(err)
			}
			saved := filepath.Join(journal.Entries[0].Workspace, "previous")
			got, err := os.ReadFile(saved)
			if err != nil || !bytes.Equal(got, edited) || !slices.Contains(preservedPaths(after), saved) {
				t.Fatal("edited policy was not retained and disclosed", err)
			}
			dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{}})
			for _, target := range d.Targets[sentinelResource] {
				got, err := os.ReadFile(target.Path)
				if err != nil || string(got) != original {
					t.Fatal("removal failed to restore the exact earlier policy", target.Path, string(got), err)
				}
			}
			got, err = os.ReadFile(saved)
			if err != nil || !bytes.Equal(got, edited) {
				t.Fatal("removal lost preserved edits", err)
			}
		})
	}
}

func TestSentinelFreshPoliciesHaveUpstreamBytesAndRemovalDeletesOnlyOwnedFiles(t *testing.T) {
	c, d := sentinelController(t)
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}})
	for _, target := range d.Targets[sentinelResource] {
		got, err := os.ReadFile(target.Path)
		if err != nil || string(got) != sentinelPolicy {
			t.Fatal("fresh policy differs from upstream, including on Windows", runtime.GOOS, err)
		}
	}
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{}})
	for _, target := range d.Targets[sentinelResource] {
		if _, err := os.Lstat(target.Path); !os.IsNotExist(err) {
			t.Fatal("new policy retained after removal", target.Path, err)
		}
	}
}

func TestSentinelAdvisesAboutCodexOverrideWithoutReadingOrChangingIt(t *testing.T) {
	c, d := sentinelController(t)
	override := filepath.Join(filepath.Dir(d.Targets[sentinelResource][0].Path), "AGENTS.override.md")
	writeConfigFixture(t, override, "Private override instruction.")
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}})
	observed, err := d.Observe(context.Background(), Resource{ID: sentinelResource}, Receipt{})
	if err != nil || !observed.Healthy || len(observed.UnverifiedApplications) != 2 || !strings.Contains(strings.Join(observed.UnverifiedApplications, "\n"), override) || strings.Contains(strings.Join(observed.UnverifiedApplications, "\n"), "Private override") {
		t.Fatal("missing or unsafe consumer advisory", observed, err)
	}
	got, err := os.ReadFile(override)
	if err != nil || string(got) != "Private override instruction." {
		t.Fatal("override was changed", err)
	}
}

func TestSentinelReusesIdenticalUnownedPolicyWithoutRemovalAuthority(t *testing.T) {
	c, d := sentinelController(t)
	for _, target := range d.Targets[sentinelResource] {
		writeConfigFixture(t, target.Path, sentinelPolicy)
	}
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}})
	state, err := LoadState(c.StatePath, c.Home)
	if err != nil || state.Receipts[sentinelResource].Ownership != "reused" || state.Receipts[sentinelResource].Recovery != "" {
		t.Fatal("matching unowned policy acquired removal authority", state, err)
	}
	dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{}})
	for _, target := range d.Targets[sentinelResource] {
		got, err := os.ReadFile(target.Path)
		if err != nil || string(got) != sentinelPolicy {
			t.Fatal("deselection removed reused policy", err)
		}
	}
}

func TestSentinelUTF16AdoptionRetainsEncodedBaselineThroughRemoval(t *testing.T) {
	for _, bom := range [][]byte{{0xff, 0xfe}, {0xfe, 0xff}} {
		c, d := sentinelController(t)
		encode, _, err := profileEncoding(bom)
		if err != nil {
			t.Fatal(err)
		}
		original := append(bytes.Clone(bom), encode("Personal café 🌍.\r\n"+sentinelBegin+"\r\nEarlier rules.\r\n"+sentinelEnd+"\r\nTrailing prose.")...)
		for _, target := range d.Targets[sentinelResource] {
			writeConfigFixture(t, target.Path, string(original))
		}
		dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{"sentinel"}, Adopt: []string{sentinelResource}})
		dispatchApproved(t, c, Request{Schema: 1, Mode: "apply", Selected: []string{}})
		for _, target := range d.Targets[sentinelResource] {
			got, err := os.ReadFile(target.Path)
			if err != nil || !bytes.Equal(got, original) {
				t.Fatal("encoded baseline was not restored", err)
			}
		}
	}
}
