package installer

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const sentinelResource = "integration.sentinel"
const sentinelVersion = "0.1.2"
const sentinelCommit = "ecafffa858666343c1639f996d177f460163e93e"
const sentinelPolicySHA256 = "efeb284196e99ee049718c1a4cd8a2090cdd41a7ce8be304cb158fc8a4d16801"

// Generated by the immutable upstream renderer, not edited or rendered at
// install time. sentinel/provenance.json records its inputs; LICENSE is MIT.
//
//go:embed sentinel/policy.md
var sentinelPolicy string

// SentinelLocations contains only process-observed consumer locations. Empty
// fields use the pinned consumers' defaults under Home, including Windows.
// In particular, ConfigHome is XDG_CONFIG_HOME, not Windows AppData.
type SentinelLocations struct {
	CodexHome, ConfigHome, PiAgentDir string
}

func configureSentinel(d *ProfileDriver, folders ConfigFolders, locations SentinelLocations) error {
	if d == nil {
		return errors.New("Sentinel requires the profile publisher")
	}
	for _, item := range []struct {
		value *string
		parts []string
	}{
		{&locations.CodexHome, []string{".codex"}},
		{&locations.ConfigHome, []string{".config"}},
		{&locations.PiAgentDir, []string{".pi", "agent"}},
	} {
		if *item.value == "" {
			*item.value = filepath.Join(append([]string{folders.Home}, item.parts...)...)
		}
	}
	for _, path := range []string{folders.Home, locations.CodexHome, locations.ConfigHome, locations.PiAgentDir} {
		if !filepath.IsAbs(path) || filepath.Clean(path) != path || strings.ContainsAny(path, "\x00\r\n") {
			return errors.New("Sentinel consumer locations must be absolute canonical native paths")
		}
	}
	targets := []ProfileTarget{
		{filepath.Join(locations.CodexHome, "AGENTS.md"), sentinelPolicy},
		{filepath.Join(folders.Home, ".claude", "CLAUDE.md"), sentinelPolicy},
		{filepath.Join(locations.ConfigHome, "opencode", "AGENTS.md"), sentinelPolicy},
		{filepath.Join(locations.PiAgentDir, "AGENTS.md"), sentinelPolicy},
	}
	for index := range targets {
		bound, err := bindConfigDestination(targets[index].Path)
		if err != nil {
			return err
		}
		targets[index].Path = bound
		for _, previous := range targets[:index] {
			if configPathsOverlap(previous.Path, bound) {
				return errors.New("Sentinel consumer policy paths overlap")
			}
		}
	}
	if d.Targets == nil {
		d.Targets = map[string][]ProfileTarget{}
	}
	d.Targets[sentinelResource] = targets
	return d.validate(sentinelResource)
}

// These are visible consumer limitations, never write authority. The override
// is inspected only for existence; its personal policy contents are not read.
func sentinelDisclosures(targets []ProfileTarget) []string {
	result := []string{"GitHub Copilot global instructions require manual user configuration; Copilot has no global policy file"}
	if len(targets) == 0 {
		return result
	}
	override := filepath.Join(filepath.Dir(targets[0].Path), "AGENTS.override.md")
	_, err := os.Lstat(override)
	if err == nil {
		result = append(result, "Codex may load "+override+" instead of Sentinel's AGENTS.md; reconcile the override manually")
	} else if !errors.Is(err, os.ErrNotExist) {
		result = append(result, fmt.Sprintf("Codex override presence could not be inspected at %s: %v", override, err))
	}
	return result
}
